"""Adicionar coluna cargo em usuarios

Revision ID: 29e0aea148f0
Revises: dfd285871be6
Create Date: 2025-08-27 21:48:37.100912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e0aea148f0'
down_revision: Union[str, Sequence[str], None] = 'dfd285871be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cargo', sa.Enum('ADMIN', 'USER', name='cargoenum'), nullable=False))
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'])
    op.alter_column('usuarios', 'ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('usuarios', 'cargo')
    # ### end Alembic commands ###
