"""Adicionar campo ativo no Paciente

Revision ID: 8dc62f4ebab0
Revises: 29e0aea148f0
Create Date: 2025-09-15 13:50:25.708337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc62f4ebab0'
down_revision: Union[str, Sequence[str], None] = '29e0aea148f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
