"""Adicionar campo ativo no Pacientes

Revision ID: d648bcd30f29
Revises: 8dc62f4ebab0
Create Date: 2025-09-15 13:56:46.603211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd648bcd30f29'
down_revision: Union[str, Sequence[str], None] = '8dc62f4ebab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('ativo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'ativo')
    # ### end Alembic commands ###
